# http://docs.travis-ci.com/user/customizing-the-build/

language: java

jdk:
 - oraclejdk9

install:
 - mvn install -Dmaven.javadoc.skip=true -Dsource.skip=true -DskipTests=true -Dgpg.skip=true

before_script:
 - _JAVA_OPTIONS="-Xmx4g -Xms1g"

script:
 - mvn clean compile test -Dgpg.skip=true

after_success:
  - mvn clean test jacoco:report coveralls:report -DrepoToken=$coveralls_token

notifications:
  email: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2